-- sudo su postgres
-- createuser clothes_user
-- createdb clothes_db --owner clothes_user
-- psql
-- alter user clothes_user with password '12345';
-- \q
-- psql clothes_db


--CLIENTES
DROP TABLE IF EXISTS customers CASCADE;
CREATE TABLE customers (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"email" character varying(100)
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON customers FROM public;
GRANT ALL ON customers TO clothes_user;

--PROVEEDORES
/*
DROP TABLE IF EXISTS suppliers CASCADE;
CREATE TABLE suppliers (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"phone" character varying(15)
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO shop_user;

REVOKE ALL ON suppliers FROM public;
GRANT ALL ON suppliers TO shop_user;*/

--PRODUCTOS
DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"price" integer,
"stock" integer,
"gender" integer
);
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON products FROM public;
GRANT ALL ON products TO clothes_user;


--COMPRAS
DROP TABLE IF EXISTS buys CASCADE;
CREATE TABLE buys (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"id_product" integer,
"id_customer" integer,
"quantity" integer,
"date" date,
   CONSTRAINT fk_products
          FOREIGN KEY(id_product) 
              REFERENCES products(id)
              ON DELETE CASCADE ,
   CONSTRAINT fk_customers
          FOREIGN KEY(id_customer) 
              REFERENCES customers(id)
              ON DELETE CASCADE 
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO clothes_user;

REVOKE ALL ON buys FROM public;
GRANT ALL ON buys TO clothes_user;


--INSERT INTO products (name, price, stock, gender) VALUES ('pantalones', 2000, 6, 1);
--INSERT INTO products (name, price, stock, gender) VALUES ('camiseta', 2200, 4, 1);